config/routes.rb
Rails.application.routes.draw do

  root 'photos#index'

  resources :photos

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  scope :newest_first, -> { order(created_at: :desc) }
  scope :most_recent_five, -> { newest_first.limit(5) }
  scope :created_before, ->(time) { where("created_at < ?", time) }

  def self.created_before(time)
    where("created_at < ?", time) 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @photos = Photo.all
    @most_recent_photos = Photo.most_recent_five

  end

  def show
    @photo = Photo.find(params[:id])
  end

  def new
    @photo = Photo.new
  end

  def edit
    @photo = Photo.find(params[:id])
  end

  def update
    @photo = Photo.find(params[:id])

    if @photo.update_attributes(photo_params)
      redirect_to photo_path(@photo)
    else
      render :edit
    end
  end

  def create
    @photo = Photo.new(photo_params)
    if @photo.save
      redirect_to photo_path(@photo)
    else
      render :new
    end
  end

  def destroy
    @photo = Photo.find(params[:id])
    @photo.delete
    redirect_to photos_path
  end

  private

  def photo_params
    params.require(:photo).permit(:title, :url, :author)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_controller_helper.rb
module PhotosControllerHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photogur</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/photos/_form.html.erb
<%= form_for @photo do |f| %>
	<div class="field"> 
	<%= f.label :title  %>
	<%= f.text_field :title %>
	</div>

<div class="field"> 
	<%= f.label :author  %>
	<%= f.text_field :author %>
</div>

<div class="field"> 
	<%= f.label :url  %>
	<%= f.text_field :url %>
</div>
<div class="actions"> 
	<%= f.submit  %>
	</div>
<% end %>

app/views/photos/edit.html.erb
<h1>New photo</h1>

<%= render 'form' %>

app/views/photos/index.html.erb
<h1>Photogur</h1>

<%= link_to "New Photo", new_photo_path(@photo)  %>
<h2>Newest Photos</h2>
<% @most_recent_photos.each do |photo|%>
	<%= link_to (image_tag photo.url), photo %>
	<%= photo.title  %>
	<%= photo.author %>
<% end %>

<h2>1 month old</h2>

<p>There are <%= Photo.created_before(1.month.ago).count %> photos older than 1 month</p>

<% unless Photo.created_before(1.month.ago).empty? %>
  <%= Photo.created_before(1.month.ago).each do |photo|%>
    <%= link_to (image_tag photo.url), photo %>
    <%= photo.title  %>
    <%= photo.author %>
  <% end %>
<% end %>

app/views/photos/new.html.erb
<h1>New photo</h1>

<%= render 'form' %>

app/views/photos/show.html.erb
<%= @photo.title  %><br \>
<%= @photo.author  %><br \>
<%= image_tag @photo.url  %>

<%= link_to 'Edit', edit_photo_path(@photo)  %>
<%= link_to 'Delete', @article, method: :delete  %>
<%= link_to 'All photos', photos_path  %>